spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: duytc
    slave:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: duytc

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true