version: '3.9'
services:
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=duytc
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/redis:/data
volumes:
  redis:

