version: '3.9'
services:
  grafana:
    image: prom/prometheus:v2.35.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=duytc
    ports:
      - '3000:3000'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - '9090:9090'


#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     restart: unless-stopped
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#       - ./prometheus_data:/prometheus
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#       - '--storage.tsdb.path=/prometheus'
#       - '--web.console.libraries=/etc/prometheus/console_libraries'
#       - '--web.console.templates=/etc/prometheus/consoles'
#       - '--web.enable-lifecycle'
#     ports:
#       - '9090'

# volumes:
#   prometheus_data: {}