spring:
  datasource:
    hikari:
      auto-commit: true
      idle-timeout: 20000
      maximum-pool-size: 2
      max-lifetime: 1800000
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.23:5432/postgres
    username: duytc
    password: duytc


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

springdoc:
  swagger-ui:
    operations-sorter: method

