spring:
  application:
    name: SpringSSO

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: anhduy12
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000
      max-lifetime: 200000
      connection-timeout: 20000
      pool-name: '[ CONNECT-DB ] ===>'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1031113005690288
            client-secret: 9d26a40af9775f52e4033be9313f7ddb
            scope: email, public_profile
          kakao:
            client-id: ed76e2a2ea00a5c50957ff1763a4b376
            client-secret: rIVftGWrmSoV9eBV5v3dqhvfCw1T9Np3
            authorization-grant-type: authorization_code
            scope: profile_nickname
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
          nave:
            client-id: ed76e2a2ea00a5c50957ff1763a4b376
            client-secret: rIVftGWrmSoV9eBV5v3dqhvfCw1T9Np3
            authorization-grant-type: authorization_code
            scope: profile_nickname
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post

        provider:
          facebook:
            authorization-uri: https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-name-attribute: id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          nave:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cors:
  allowed:
    origins: "http://localhost:4200"
    methods: "GET,POST,PUT,DELETE"
    headers: "Content-Type,Authorization"
  permit-all:
    endpoint:
      /swagger-ui/**,
      /v3/api-docs/**,
      /swagger-resources/**,
      /webjars/**,
      /api/auth/**,

logging:
  level:
    org.springframework.security.oauth2: DEBUG


#  http://localhost:8080/oauth2/authorization/facebook
#  http://localhost:8080/oauth2/authorization/kakao