--LIQUIBASE FORMATTED SQL

--CHANGESET DUYTC:CREATE-CATEGORY-TABLE
CREATE TABLE CATEGORIES
(
    CATEGORY_ID   VARCHAR(36)                         NOT NULL,
    NAME          VARCHAR(100)                        NOT NULL,
    DESCRIPTION   VARCHAR(500),
    DISPLAY_ORDER INT       DEFAULT 0                 NOT NULL,
    ENABLED       BOOLEAN   DEFAULT TRUE              NOT NULL,
    CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_DATE  TIMESTAMP,

    CONSTRAINT CATEGORIES_PKEY PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UK_CATEGORIES_NAME UNIQUE (NAME)
);

COMMENT
ON TABLE CATEGORIES IS 'LƯU THÔNG TIN DANH MỤC';

COMMENT
ON COLUMN CATEGORIES.CATEGORY_ID IS 'MÃ ĐỊNH DANH DUY NHẤT CỦA DANH MỤC, ĐƯỢC SINH BỞI ỨNG DỤNG DƯỚI DẠNG CHUỖI UUID';
COMMENT
ON COLUMN CATEGORIES.NAME IS 'TÊN DANH MỤC';
COMMENT
ON COLUMN CATEGORIES.DESCRIPTION IS 'MÔ TẢ DANH MỤC';
COMMENT
ON COLUMN CATEGORIES.DISPLAY_ORDER IS 'THỨ TỰ HIỂN THỊ CỦA DANH MỤC';
COMMENT
ON COLUMN CATEGORIES.ENABLED IS 'TRẠNG THÁI DANH MỤC. TRUE LÀ ĐANG HOẠT ĐỘNG, FALSE LÀ KHÔNG HOẠT ĐỘNG HOẶC ĐÃ XÓA MỀM';
COMMENT
ON COLUMN CATEGORIES.CREATED_DATE IS 'THỜI ĐIỂM TẠO DANH MỤC';
COMMENT
ON COLUMN CATEGORIES.UPDATED_DATE IS 'THỜI ĐIỂM CẬP NHẬT DANH MỤC GẦN NHẤT';

CREATE INDEX IDX_CATEGORIES_ENABLED
    ON CATEGORIES (ENABLED);

CREATE INDEX IDX_CATEGORIES_CREATED_DATE
    ON CATEGORIES (CREATED_DATE);

CREATE INDEX IDX_CATEGORIES_DISPLAY_ORDER
    ON CATEGORIES (DISPLAY_ORDER);

--ROLLBACK DROP TABLE IF EXISTS CATEGORIES;