server:
  port: 8083

spring:
  datasource:
    hikari:
      auto-commit: true
      idle-timeout: 20000
      maximum-pool-size: 2
      max-lifetime: 1800000
      connection-timeout: 20000
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: keycloak
      password: duytc
      driver-class-name: org.postgresql.Driver

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: keycloak
    password: duytc

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true


keycloak-initializer:
  realm: example
  client-id: duytc-app
#  ssl-required: external
  username: admin
  password: duytc
  auth-server-url: http://localhost:8080/auth/
  credentials-secret: gkDYbl6xqQ0fVMhYVXsoZ5CeZi6168gK

