server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: anhduy12
    hikari:
      auto-commit: true
      idle-timeout: 20000
      maximum-pool-size: 2
      max-lifetime: 200000
      connection-timeout: 20000
      pool-name: '[ CONNECT ] ===>'

  liquibase:
    change-log: classpath:liquibase/main-changelog.yml
    clear-checksums: true

  security:
    access-token: 9QZaVt1gRjmNWtEPksgNaJ7OT6OmnbNQxxx334sdeaFxxx1
    access-token-time: 900000
    refresh-token: 9QZaVt1gRjmNWtEPksgNaJ7OT6OmnbNQxxx334sdeaFxxx2
    refresh-token-time: 900000

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: hulkhulk1245@gmail.com
    password: tcjdgzuimnyzrfsi
    mail-from: hulkhulk1245@gmail.com
    protocol: smtp
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  freemarker:
    template-loader-path: classpath:/templates/mail
    suffix: .ftlh
    cache: true
    charset: UTF-8

springdoc:
  api-docs:
    url-product: http://localhost:8080
    url-dev: http://localhost:8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.example.springsecurity.requests, org.example.springsecurity.responses
  type-handlers-package: org.example.springsecurity.util
  mapper-locations: /mybatis/*.xml

cors:
  allowed:
    origins: "http://localhost:4200"
    methods: "GET,POST,PUT,DELETE"
    headers: "Content-Type,Authorization"

